### PR TITLE
parsing for Post's thumbnail property

### PR DESCRIPTION
**Pull request by vrkmajeti**

### CODE REVIEW

**Comment by Kacks** [comment]
Over 1 year old, going to close in a couple of days.

**Comment by Kacks** [comment]
No Activity

**Comment by clitvin** [comment]
I still get these notifications :)

**Comment by Kacks** [comment]
Hey @clitvin!!!  Hope life is treating you well!!

One thing you can do is check your setting, and make sure you've removed notifications for these repos.  I've asked the team to see if they can do anything on our end.

**Comment by sglazer** [comment]
Hey Guys! I'm getting these too :)


________________________________

**Comment by Dar** [comment]
Looks good !
You can go ahead and push! Lol
:P

**Comment by Kacks** [comment]
Miss you guys!!!!

It's a public Repo you have to all have to unsubscribe:
https://github.com/notifications

**Comment by adamlapczynski** [comment]
What if we don't want to unsubscribe?? ;)

**Comment by augustorosa** [comment]
yes i enjoy the emails :)

**Comment by yfesenko** [comment]
Keep it professional, boys, but this is an extremely warm blast from the past!

**Comment by Kacks** [comment]
@adamlapczynski Then you can listen, and please provide some feedback!!

**Comment by yodavethomas** [comment]
@adamlapczynski @yfesenko @augustorosa @sglazer you're all ghosts. All of you.

**Comment by kevcenteno** [comment]
@yodavethomas Boo.

**Comment by yodavethomas** [comment]
streams

Bout to cross the streams on all of you.

**Pull request closed without merging**
